apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels: 
    app: mydeployment
spec:
  replicas: 3
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app: mydeployment
  template:
    metadata:
      labels:
        app: mydeployment
    spec:
      containers:
      - name: myhttpd
        image: httpd
        ports:
        - containerPort: 80
