apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicationcrtl
spec:
  replicas: 3
  selector:
    app: myreplicationCrtlpod
  template:
    metadata:
      name: myreplicationCrtlpod
      labels:
        app: myreplicationCrtlpod
    spec:
      containers:
        - name: mynginx
          image: nginx:latest
          ports:
            - containerPort: 80

